### ISSUE TITLE
How to disable text or description for a portal_type only ?

### ISSUE THREAD

**Issue by sgeulette** [collective/collective.dexteritytextindexer#41]
Hello,
After this issue #2, decision was taken to tag IBasic title and description fields as searchable.
I agree you can remove this with `no_longer_searchable` function.
But it's for all types using this behavior.

If I want to remove title and description only for a specific portal type, how to do ?
A solution could be to filter fields in `get_searchable_contexts_and_fields` by removing those gotten from another named adapter, that could be registered by "portal_type".
What do you think ?

@jone @mauritsvanrees @jensens

**Comment by jone** [comment]
Hey @sgeulette 

Yes, the "searchable" tagged value is basically stored per behavior interface. If you want to `get_searchable_contexts_and_fields` you'd probably have to monkey patch it, since it is not an adapter. I'd awoid monkey patching. So you have these options:


1. Make a custom behavior, which behaves differently. You could probably subclass `IBasic` and then use `no_longer_searchable`.
2. You could register a custom [`dynamic_searchable_text_indexer`](https://github.com/collective/collective.dexteritytextindexer/blob/d120ee87f5bd35451d54be4c800fb7d29efeb32b/collective/dexteritytextindexer/indexer.py#L40-L41) for your custom type. But you'd have to copy the whole method, which is not very nice.
3. You could register a [custom field converter adapter](https://github.com/collective/collective.dexteritytextindexer/blob/d120ee87f5bd35451d54be4c800fb7d29efeb32b/collective/dexteritytextindexer/indexer.py#L77-L79) for your specific FTI (based on the schema interface) and and for this type of field. You cannot register the adapter by field name though, you'd have to take care of the other fields in the adapter.

I'd probably go with 1. 😉

**Comment by sgeulette** [comment]
Hi @jone 
Thanks for your fast reply.
I didn't think to the converter...
It's my preferred solution.
Implemented in collective.contact.core to[ escape title and description](https://github.com/collective/collective.contact.core/blob/3fa39a9f121c4092fe57eeb2ba1437f7e1149ef1/src/collective/contact/core/indexers.py#L156).
Have a good day.
